name: Top 2000 App WhiteSource Bolt Check -

trigger: none 
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

pool:
  name: At Home

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  displayName: 'Nuget restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: WhiteSource Bolt@20
  displayName: 'WhiteSource Bolt'
