steps:

  - task: DownloadSecureFile@1
    name: signingCert
    displayName: 'Download WindowsStore certificate'
    inputs:
      secureFile: 'WindowsStore.pfx'

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.8.0'
    inputs:
      versionSpec: 5.8.0

  - task: NuGetCommand@2
    displayName: 'Nuget restore'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: VersionAPPX@2
    inputs:
      Path: '$(Build.SourcesDirectory)'
      VersionNumber: '$(uwp-version)'
      InjectVersion: False
      VersionRegex: '(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){3}'
      OutputVersion: 'OutputedVersion'

  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: '**\*.sln'
      platform: 'x86'
      configuration: 'Release'
      msbuildArgs:  '/p:AppxBundlePlatforms="x86|x64|ARM"
                     /p:AppxPackageDir="$(build.artifactStagingDirectory)\AppxPackages\\"
                     /p:AppxBundle=Always 
                     /p:UapAppxPackageBuildMode=StoreUpload
                     /p:AppxPackageSigningEnabled=true
                     /p:PackageCertificateThumbprint="" 
                     /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)"
                     /p:PackageCertificatePassword="$(WindowsStorePfxPassword)"'

  - task: VSTest@2
    displayName: 'Test - Unittests'
    inputs:
      testSelector: 'testAssemblies'
      codeCoverageEnabled: true
      testAssemblyVer2: |
        **\*Unittests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - publish: '$(build.artifactStagingDirectory)\AppxPackages'
    displayName: 'Publishing WindowsStore Artifacts'
    artifact: UWP