trigger: none

pr:
- main

variables:
- template: version.yml
- name: product
  value: 'TOP2000'

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 6.8.0'
    inputs:
      versionSpec: 6.8.0

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11.0.21+9'
      jdkArchitectureOption: 'x86'
      jdkSourceOption: 'PreInstalled'

  - task: NuGetCommand@2
    displayName: 'Nuget restore'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: '**\*.sln'
      platform: 'x86'
      configuration: 'Release'
      msbuildArgs:  '/p:AppxBundle=Never
                     /p:AppxPackageSigningEnabled=false'

  - task: VSTest@2
    displayName: 'Test - Unittests'
    inputs:
      testSelector: 'testAssemblies'
      codeCoverageEnabled: true
      testAssemblyVer2: |
        **\*Unittests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'