variables:
- group: Top-2000-variable-group
- template: version.yml
- name: product
  value: 'TOP2000'

trigger: none
pr: none

steps:

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '2d33193a-77fd-4ddc-be87-12c73bc5ff99'
    definition: '60'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    allowFailedBuilds: true
    artifactName: 'UWP'
    targetPath: '$(Pipeline.Workspace)\UWP'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)\AppxPackages'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'
    replaceExistingArchive: true

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'AppCenter'
    appSlug: 'Chroomsoft/TOP2000-UWP'
    appFile: '$(Build.ArtifactStagingDirectory)/release.zip'
    symbolsOption: 'UWP'
    appxsymPath: 'symbol-path'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Automation'
    destinationType: 'groups'

#stages:
#- stage: Build
#  jobs:
#  - job: Build
#    pool:
#      name: At Home
#    steps:
#    - template: uwp-build.yml