//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chroomsoft.Top2000.Apps.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chroomsoft.Top2000.Apps.Globalisation.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze app toont de Top 2000 lijst sinds het jaar 1999 en toont statistieken van een plaat..
        /// </summary>
        internal static string AboutThisApp {
            get {
                return ResourceManager.GetString("AboutThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noteringen.
        /// </summary>
        internal static string Appearances {
            get {
                return ResourceManager.GetString("Appearances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artiest.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuele positie tonen.
        /// </summary>
        internal static string AutomaticallyScroll {
            get {
                return ResourceManager.GetString("AutomaticallyScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Chroomsoft. All rechten voorbehouden.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body {
        ///                font-family: &quot;Calibri&quot;,&quot;sans-serif&quot;;
        ///                font-size: 14px;
        ///            }
        ///            h1, h2 {
        ///                font-size: 14px;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div&gt;
        ///            &lt;h1&gt;THIRD PARTY CODE NOTICE&lt;/h1&gt;
        ///            &lt;p&gt;
        ///                This software is based on or includes material from the projects listed below. Please Note: Chroomsoft, Top2000, Rick Neeft, is not the original [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donker.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontwikkeld door Rick Neeft.
        /// </summary>
        internal static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE MAKER VAN DEZE APP IS NIET AANSPRAKELIJK NOCH VERANTWOORDELIJK VOOR DE JUISTHEID VAN DE INFORMATIE GETOOND BINNEN DEZE APP. DIT IS GEEN OFFICELE APP VAN DE NEDERLANDSE PUBLIEKE OMROEP..
        /// </summary>
        internal static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groeperen op: {0}.
        /// </summary>
        internal static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groeperen op.
        /// </summary>
        internal static string GroupByHeader {
            get {
                return ResourceManager.GetString("GroupByHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Top 2000.
        /// </summary>
        internal static string InTop2000 {
            get {
                return ResourceManager.GetString("InTop2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een group.
        /// </summary>
        internal static string JumpToGroup {
            get {
                return ResourceManager.GetString("JumpToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal voorkeur.
        /// </summary>
        internal static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer de taal voor deze app..
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste positie.
        /// </summary>
        internal static string LastPosition {
            get {
                return ResourceManager.GetString("LastPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste notering in de Top 2000 (lijst 2019).
        /// </summary>
        internal static string LatestPlayTime {
            get {
                return ResourceManager.GetString("LatestPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licht.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niks.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        internal static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of bezoek ons op Facebook op.
        /// </summary>
        internal static string OrVisitFacebook {
            get {
                return ResourceManager.GetString("OrVisitFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positie.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body {
        ///                font-family: &quot;Calibri&quot;,&quot;sans-serif&quot;;
        ///                font-size: 14px;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Top 2000 App Privacy Verklaring&lt;/h1&gt;
        ///&lt;p&gt;Uw privacy is belangrijk. In dit privacy statement wordt u op de hoogte gehouden hoe de applicatie gegevens verwerkt en waarom. Wanneer u gebruikt maakt van de app gaat u akkoord met dit privacy statement.&lt;/p&gt;
        ///&lt;h3&gt;Welke gegevens worden verzameld&lt;/h3&gt;
        ///&lt;p&gt;Voor een bet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja!.
        /// </summary>
        internal static string RateIt {
            get {
                return ResourceManager.GetString("RateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herinner het me later.
        /// </summary>
        internal static string RateNotNow {
            get {
                return ResourceManager.GetString("RateNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij zouden heel graag willen weten wat u ervan vindt. Zou u even de tijd willen nemen om deze app te beoordelen en waarderen?.
        /// </summary>
        internal static string RateText {
            get {
                return ResourceManager.GetString("RateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor het uitproberen van de Top 2000 App..
        /// </summary>
        internal static string RateTitle {
            get {
                return ResourceManager.GetString("RateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoogste.
        /// </summary>
        internal static string RecordHigh {
            get {
                return ResourceManager.GetString("RecordHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laagste.
        /// </summary>
        internal static string RecordLow {
            get {
                return ResourceManager.GetString("RecordLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resultaten gevonden.
        /// </summary>
        internal static string ResultFoundHeader {
            get {
                return ResourceManager.GetString("ResultFoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen resultaten gevonden.
        /// </summary>
        internal static string ResultNotFound {
            get {
                return ResourceManager.GetString("ResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resultaten gevonden.
        /// </summary>
        internal static string ResultsFound {
            get {
                return ResourceManager.GetString("ResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek in Top 2000.
        /// </summary>
        internal static string SearchTop2000 {
            get {
                return ResourceManager.GetString("SearchTop2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een editie.
        /// </summary>
        internal static string SelectEdition {
            get {
                return ResourceManager.GetString("SelectEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een thema.
        /// </summary>
        internal static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon huidige tijd.
        /// </summary>
        internal static string ShowCurrentGroup {
            get {
                return ResourceManager.GetString("ShowCurrentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon geselecteerde jaar.
        /// </summary>
        internal static string ShowSelectedTrack {
            get {
                return ResourceManager.GetString("ShowSelectedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinds ontstaan.
        /// </summary>
        internal static string SinceRelease {
            get {
                return ResourceManager.GetString("SinceRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorteer op: {0}.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorteer op.
        /// </summary>
        internal static string SortByHeader {
            get {
                return ResourceManager.GetString("SortByHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik systeem instellingen.
        /// </summary>
        internal static string SystemTheme {
            get {
                return ResourceManager.GetString("SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getest door Bhavna Devi Ruttun.
        /// </summary>
        internal static string TestedBy {
            get {
                return ResourceManager.GetString("TestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema.
        /// </summary>
        internal static string ThemeMode {
            get {
                return ResourceManager.GetString("ThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party.
        /// </summary>
        internal static string ThirdParty {
            get {
                return ResourceManager.GetString("ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benader.
        /// </summary>
        internal static string ToContact {
            get {
                return ResourceManager.GetString("ToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hebben een nieuwe Top 2000 lijst gedownload. Herstart de app om deze versie te gebruiken..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe Top 2000 lijst beschikbaar.
        /// </summary>
        internal static string UpdateAvailableHeader {
            get {
                return ResourceManager.GetString("UpdateAvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekijk per datum.
        /// </summary>
        internal static string ViewByDate {
            get {
                return ResourceManager.GetString("ViewByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezoek de officele NPO Top 2000 website op:.
        /// </summary>
        internal static string VisitTop2000Site {
            get {
                return ResourceManager.GetString("VisitTop2000Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Top 2000 is jaarlijks radioprogramma van Radio 2. Het wordt uitgezonden vanaf 8 uur op Eerste Kerstdag tot oudjaarsnacht.  .
        /// </summary>
        internal static string WhatIsTop2000 {
            get {
                return ResourceManager.GetString("WhatIsTop2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar overzicht.
        /// </summary>
        internal static string YearsOverview {
            get {
                return ResourceManager.GetString("YearsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open YouTube.
        /// </summary>
        internal static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
